// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230129055209_alimentar tabla villa")]
    partial class alimentartablavilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MetrosCuadrados")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifia")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Detalle de la via",
                            FechaActualizacion = new DateTime(2023, 1, 28, 23, 52, 9, 622, DateTimeKind.Local).AddTicks(896),
                            FechaCreacion = new DateTime(2023, 1, 28, 23, 52, 9, 622, DateTimeKind.Local).AddTicks(849),
                            ImagenUrl = "",
                            MetrosCuadrados = 50.0,
                            Nombre = "villa real",
                            Ocupantes = 5,
                            Tarifia = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Detalle de la via",
                            FechaActualizacion = new DateTime(2023, 1, 28, 23, 52, 9, 622, DateTimeKind.Local).AddTicks(902),
                            FechaCreacion = new DateTime(2023, 1, 28, 23, 52, 9, 622, DateTimeKind.Local).AddTicks(901),
                            ImagenUrl = "",
                            MetrosCuadrados = 40.0,
                            Nombre = "premium real",
                            Ocupantes = 4,
                            Tarifia = 150.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
